### PR TITLE
Fix treemanager includes

### PR DESCRIPTION
**Pull request by lukedirtwalker**
This makes the whole compilation a bit lighter
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/198%23issuecomment-152487433%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/198%23issuecomment-152488326%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/198%23issuecomment-152488450%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/198%23issuecomment-152487433%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hey%2C%20thanks%20a%20lot%20for%20this.%20Does%20it%20perceptively%20speed%20up%20compilation%3F%20How/why%20did%20you%20hunt%20down%20these%20issues%3F%22%2C%20%22created_at%22%3A%20%222015-10-30T10%3A31%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20not%20sure%2C%20it%20used%206%3A18%20for%20a%20clean%20build%20%28clang%203.7%20-j4%2C%20including%20the%20generated%20AstApi%29.%5Cr%5Cn%5Cr%5CnWe%20saw%20yesterday%20the%20AllTreeManager%20include%20in%20Node.h%20thus%20I%20decided%20to%20check%20if%20it%20is%20really%20needed.%20Then%20checked%20where%20else%20it%20is%20included%20and%20if%20it%20is%20really%20needed.%20Then%20I%20also%20quickly%20checked%20who%20includes%20TreeManager%22%2C%20%22created_at%22%3A%20%222015-10-30T10%3A34%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22Cool.%20Thanks%20%3A%29%22%2C%20%22created_at%22%3A%20%222015-10-30T10%3A35%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/198#issuecomment-152487433'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> Hey, thanks a lot for this. Does it perceptively speed up compilation? How/why did you hunt down these issues?
- <a href='https://github.com/lukedirtwalker'></a> I'm not sure, it used 6:18 for a clean build (clang 3.7 -j4, including the generated AstApi).
  We saw yesterday the AllTreeManager include in Node.h thus I decided to check if it is really needed. Then checked where else it is included and if it is really needed. Then I also quickly checked who includes TreeManager
- <a href='https://github.com/dimitar-asenov'></a> Cool. Thanks :)

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/198?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/198?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/198'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/dimitar-asenov/Envision/pull/198'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dimitar-asenov** [comment]
Hey, thanks a lot for this. Does it perceptively speed up compilation? How/why did you hunt down these issues?

**Comment by lukedirtwalker** [comment]
I'm not sure, it used 6:18 for a clean build (clang 3.7 -j4, including the generated AstApi). But I don't have a reference value.

We saw yesterday the AllTreeManager include in Node.h thus I decided to check if it is really needed. Then checked where else it is included and if it is really needed. Then I also quickly checked who includes TreeManager

**Comment by dimitar-asenov** [comment]
Cool. Thanks :)

**Pull request merged**
