### PR TITLE
Add a profiling sample

### PR DESCRIPTION
**Pull request by lukedirtwalker**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/169%23issuecomment-148013691%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/169%23issuecomment-148017225%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/169%23issuecomment-148018683%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/169%23issuecomment-148013691%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Alright%2C%20could%20you%20please%20remove%20the%20file%2C%20and%20extend%20the%20README%20file%20with%20the%20link%20and%20downloading%20it%20as%20the%20first%20step.%5Cr%5Cn%5Cr%5CnHaving%20no%20specific%20license%20can%2C%20unfortunately%2C%20mean%20in%20some%20cases%20that%20the%20code%20is%20more%20restricted%2C%20than%20if%20it%20was%20published%20explicitly%20with%20a%20permissive%20license.%22%2C%20%22created_at%22%3A%20%222015-10-14T10%3A52%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22Okay%20I%20amended%20to%20commit%20according%20to%20the%20discussion.%22%2C%20%22created_at%22%3A%20%222015-10-14T11%3A02%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks.%22%2C%20%22created_at%22%3A%20%222015-10-14T11%3A06%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/169#issuecomment-148013691'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> Alright, could you please remove the file, and extend the README file with the link and downloading it as the first step.
  Having no specific license can, unfortunately, mean in some cases that the code is more restricted, than if it was published explicitly with a permissive license.
- <a href='https://github.com/lukedirtwalker'></a> Okay I amended to commit according to the discussion.
- <a href='https://github.com/dimitar-asenov'></a> Thanks.

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/169?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/169?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/169'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/dimitar-asenov/Envision/pull/169'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dimitar-asenov** [comment]
Alright, could you please remove the file, and extend the README file with the link and downloading it as the first step.

Having no specific license can, unfortunately, mean in some cases that the code is more restricted, than if it was published explicitly with a permissive license.

**Comment by lukedirtwalker** [comment]
Okay I amended to commit according to the discussion.

**Comment by dimitar-asenov** [comment]
Thanks.

**Pull request merged**
