### PR TITLE
Cpp Export: Print Context

### PR DESCRIPTION
**Pull request by patrick-luethi**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/305%23issuecomment-179229320%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/305%23issuecomment-179315403%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/305%23issuecomment-179229320%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22OK%20I%27m%20done%20reviewing.%20It%20looks%20like%20a%20promising%20direction.%20I%27m%20looking%20forward%20to%20the%20other%20changes%20that%20you%20wanted%20to%20make.%22%2C%20%22created_at%22%3A%20%222016-02-03T13%3A27%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22done%202.0%22%2C%20%22created_at%22%3A%20%222016-02-03T16%3A06%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6049349%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/patrick-luethi%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/305#issuecomment-179229320'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> OK I'm done reviewing. It looks like a promising direction. I'm looking forward to the other changes that you wanted to make.
- <a href='https://github.com/patrick-luethi'></a> done 2.0

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/305?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/305?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/305'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/dimitar-asenov/Envision/pull/305'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dimitar-asenov** [comment]
OK I'm done reviewing. It looks like a promising direction. I'm looking forward to the other changes that you wanted to make.

**Comment by patrick-luethi** [comment]
done

**Comment by patrick-luethi** [comment]
done 2.0

**Pull request merged**
