### PR TITLE
Minor fixes after clang --analyze run

### PR DESCRIPTION
**Pull request by lukedirtwalker**
-We shouldn't call delete on new[] allocated stuff, thus we replace
SAFE_DELETE with actual delete[] calls.
-Consistenly check the error with checkError, before there were some
errorCode write locations which were never read.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/188%23issuecomment-150811759%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/188%23issuecomment-150811815%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/188%23issuecomment-150811857%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/188%23issuecomment-150811894%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/188%23issuecomment-150811958%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/188%23issuecomment-150811759%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Sweet%21%20thanks.%20Didn%27t%20clang%20analyze%20find%20a%20ton%20of%20other%20issues%3F%22%2C%20%22created_at%22%3A%20%222015-10-24T13%3A27%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22Not%20a%20ton%20but%20many.%20But%20most%20are%20false%20positives%20I%20think.%22%2C%20%22created_at%22%3A%20%222015-10-24T13%3A28%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27d%20be%20curious%20to%20have%20a%20look%2C%20but%20maybe%20next%20week%20at%20ETH.%20My%20schedule%20is%20quite%20full%20this%20weekend.%22%2C%20%22created_at%22%3A%20%222015-10-24T13%3A29%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sure%2C%20there%20are%20some%20which%20could%20be%20interesting%20to%20look%20at.%20Have%20a%20nice%20weekend.%22%2C%20%22created_at%22%3A%20%222015-10-24T13%3A30%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%2C%20you%20too.%22%2C%20%22created_at%22%3A%20%222015-10-24T13%3A31%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/188#issuecomment-150811759'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> Sweet! thanks. Didn't clang analyze find a ton of other issues?
- <a href='https://github.com/lukedirtwalker'></a> Not a ton but many. But most are false positives I think.
- <a href='https://github.com/dimitar-asenov'></a> I'd be curious to have a look, but maybe next week at ETH. My schedule is quite full this weekend.
- <a href='https://github.com/lukedirtwalker'></a> Sure, there are some which could be interesting to look at. Have a nice weekend.
- <a href='https://github.com/dimitar-asenov'></a> Thanks, you too.

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/188?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/188?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/188'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
Sweet! thanks. Didn't clang analyze find a ton of other issues?

**Comment by lukedirtwalker** [comment]
Not a ton but many. But most are false positives I think.

**Comment by dimitar-asenov** [comment]
I'd be curious to have a look, but maybe next week at ETH. My schedule is quite full this weekend.

**Comment by lukedirtwalker** [comment]
Sure, there are some which could be interesting to look at. Have a nice weekend.

**Comment by dimitar-asenov** [comment]
Thanks, you too.

**Pull request merged**
