### PR TITLE
WIP: Cpp Import/Export

### PR DESCRIPTION
**Pull request by patrick-luethi**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/307%23issuecomment-182067121%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/307%23issuecomment-182277468%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/307%23issuecomment-182279994%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/307%23issuecomment-182067121%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Alright%2C%20I%27m%20done%20with%20the%20reivew.%20Please%20fix%20these%20issues%20in%20additional%20commits%20to%20this%20PR%2C%20before%20doing%20other%20stuff%20%28and%20please%20don%27t%20insert%20any%20additional%20work%2C%20just%20the%20fixes%20%3A%29%20%29%22%2C%20%22created_at%22%3A%20%222016-02-09T21%3A03%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22done%22%2C%20%22created_at%22%3A%20%222016-02-10T09%3A35%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6049349%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/patrick-luethi%22%7D%7D%2C%20%7B%22body%22%3A%20%22Great%2C%20thanks.%22%2C%20%22created_at%22%3A%20%222016-02-10T09%3A42%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/307#issuecomment-182067121'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> Alright, I'm done with the reivew. Please fix these issues in additional commits to this PR, before doing other stuff (and please don't insert any additional work, just the fixes :) )
- <a href='https://github.com/patrick-luethi'></a> done
- <a href='https://github.com/dimitar-asenov'></a> Great, thanks.

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/307?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/307?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/307'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/dimitar-asenov/Envision/pull/307'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dimitar-asenov** [comment]
Alright, I'm done with the reivew. Please fix these issues in additional commits to this PR, before doing other stuff (and please don't insert any additional work, just the fixes :) )

**Comment by patrick-luethi** [comment]
done

**Comment by dimitar-asenov** [comment]
Great, thanks.

**Pull request merged**
