### PR TITLE
Add some scripts

### PR DESCRIPTION
**Pull request by lukedirtwalker**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/246%23issuecomment-162567409%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/246%23issuecomment-162567741%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/246%23issuecomment-162574339%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/246%23issuecomment-162567409%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20scripts%20are%20in%20the%20evaluation%20folder.%20Will%20these%20be%20automatically%20picked%20up%20by%20the%20current%20prompt%3F%20If%20not%20we%20should%20make%20the%20implementation%20recurse%20through%20whatever%20is%20in%20./scripts/%20to%20find%20all%20scripts.%20You%20might%20need%20to%20rerun%20qmake%20in%20order%20to%20pick%20the%20new%20scripts%20as%20install%20targets.%22%2C%20%22created_at%22%3A%20%222015-12-07T16%3A01%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yeah%20you%20just%20have%20to%20type%20it%20so%3A%20%60%60%60evaluation/scriptName%60%60%60%22%2C%20%22created_at%22%3A%20%222015-12-07T16%3A02%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22OK%2C%20thanks.%22%2C%20%22created_at%22%3A%20%222015-12-07T16%3A20%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/246#issuecomment-162567409'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> The scripts are in the evaluation folder. Will these be automatically picked up by the current prompt? If not we should make the implementation recurse through whatever is in ./scripts/ to find all scripts. You might need to rerun qmake in order to pick the new scripts as install targets.
- <a href='https://github.com/lukedirtwalker'></a> Yeah you just have to type it so: `evaluation/scriptName`
- <a href='https://github.com/dimitar-asenov'></a> OK, thanks.

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/246?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/246?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/246'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/dimitar-asenov/Envision/pull/246'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dimitar-asenov** [comment]
The scripts are in the evaluation folder. Will these be automatically picked up by the current prompt? If not we should make the implementation recurse through whatever is in ./scripts/ to find all scripts. You might need to rerun qmake in order to pick the new scripts as install targets.

**Comment by lukedirtwalker** [comment]
Yeah you just have to type it so: `evaluation/scriptName`

**Comment by dimitar-asenov** [comment]
OK, thanks.

**Pull request merged**
