### PR TITLE
Add an example of how we could do code analysis scripts

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Just another idea that came to my mind :P
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/dimitar-asenov/Envision/pull/345%23issuecomment-196716633%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/345%23issuecomment-196766960%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/345%23issuecomment-197005838%22%2C%20%22https%3A//github.com/dimitar-asenov/Envision/pull/345%23issuecomment-197211466%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov/Envision/pull/345%23issuecomment-196716633%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20is%20interesting.%20Can%20you%20show%20me%20a%20screenshot%3F%22%2C%20%22created_at%22%3A%20%222016-03-15T08%3A30%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20is%20the%20same%20as%20a%20compiler%20warning%2C%20but%20I%20can%20do%20a%20screenshot%20tonight.%22%2C%20%22created_at%22%3A%20%222016-03-15T11%3A05%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22Updated%5Cr%5Cn%21%5Bscreenshot_20160315_212851%5D%28https%3A//cloud.githubusercontent.com/assets/3530769/13792847/3ce6b33a-eaf4-11e5-80de-e47730510776.png%29%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-15T20%3A24%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3530769%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lukedirtwalker%22%7D%7D%2C%20%7B%22body%22%3A%20%22Cool%2C%20thanks.%22%2C%20%22created_at%22%3A%20%222016-03-16T08%3A32%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1152976%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dimitar-asenov%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/dimitar-asenov/Envision/pull/345#issuecomment-196716633'>General Comment</a></b>
- <a href='https://github.com/dimitar-asenov'></a> This is interesting. Can you show me a screenshot?
- <a href='https://github.com/lukedirtwalker'></a> It is the same as a compiler warning, but I can do a screenshot tonight.
- <a href='https://github.com/lukedirtwalker'></a> Updated
  screenshot_20160315_212851
- <a href='https://github.com/dimitar-asenov'></a> Cool, thanks.

<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/345?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/dimitar-asenov/Envision/pull/345?approve=1'></a>&nbsp;<a href='https://github.com/dimitar-asenov/Envision/pull/345'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dimitar-asenov** [comment]
This is interesting. Can you show me a screenshot?

**Comment by lukedirtwalker** [comment]
It is the same as a compiler warning, but I can do a screenshot tonight.

**Comment by lukedirtwalker** [comment]
Updated
screenshot_20160315_212851

**Comment by dimitar-asenov** [comment]
Cool, thanks.

**Pull request merged**
