### PR TITLE
Make FormalArgument a subclass of VariableDeclaration

### PR DESCRIPTION
**Pull request by lukedirtwalker**
An argument really is a special kind of variable declaration, therefore
it makes sense to model this as such.

### CODE REVIEW

**Comment by lukedirtwalker** [comment]
Note that if you like this, please leave it open as I will adapt the debugger implementation to use this.

**Comment by dimitar-asenov** [comment]
Thanks a lot for this Lukas.

This generally looks fine, I'm just wondering if we need to do anything regarding FormalResult and FormalTypeArgument. I think we could at least adapt formal result as well.

In any case, I will accept this eventually so feel free to adapt the debugger implementation.

**Comment by lukedirtwalker** [comment]
I think this would be ready to be merged. 

**Note** it will break all existing Envision projects. (Will have to be re-imported)

**Comment by dimitar-asenov** [comment]
Thanks Lukas!

**Pull request merged**
